/**
 * constants.js
 * 
 * OPL Decompiler Constants
 * Contains QCode definitions and Precedence rules.
 */

const QCODE_DEFS = {
    0X00: { args: 'v', pops: '', pushes: 'I', desc: 'Push local/global int' },
    0X01: { args: 'v', pops: '', pushes: 'F', desc: 'Push local/global float' },
    0X02: { args: 'v', pops: '', pushes: 'S', desc: 'Push local/global string' },
    0X03: { args: 'V', pops: '', pushes: 'I', desc: 'Push local/global int array element' },
    0X04: { args: 'V', pops: '', pushes: 'F', desc: 'Push local/global float array element' },
    0X05: { args: 'V', pops: '', pushes: 'S', desc: 'Push local/global string array element' },
    0X06: { args: 'W', pops: '', pushes: 'F', desc: 'Push calculator memory' },
    0X07: { args: 'v', pops: '', pushes: 'I', desc: 'Push extern int' },
    0X08: { args: 'v', pops: '', pushes: 'F', desc: 'Push extern float' },
    0X09: { args: 'v', pops: '', pushes: 'S', desc: 'Push extern string' },
    0X0A: { args: 'v', pops: '', pushes: 'I', desc: 'Push extern int array element' },
    0X0B: { args: 'v', pops: '', pushes: 'F', desc: 'Push extern float array element' },
    0X0C: { args: 'v', pops: '', pushes: 'S', desc: 'Push extern string array element' },
    0X0D: { args: 'v', pops: '', pushes: 'I', desc: 'Push local/global int ref' },
    0X0E: { args: 'v', pops: '', pushes: 'F', desc: 'Push local/global float ref' },
    0X0F: { args: 'v', pops: '', pushes: 'S', desc: 'Push local/global string ref' },
    0X10: { args: 'v', pops: 'I', pushes: 'I', desc: 'Push local/global int array ref' },
    0X11: { args: 'v', pops: 'I', pushes: 'F', desc: 'Push local/global float array ref' },
    0X12: { args: 'v', pops: 'I', pushes: 'S', desc: 'Push local/global string array ref' },
    0X13: { args: 'W', pops: '', pushes: 'F', desc: 'Push calculator memory ref' },
    0X14: { args: 'V', pops: '', pushes: 'I', desc: 'Push extern int ref' },
    0X15: { args: 'V', pops: '', pushes: 'F', desc: 'Push extern float ref' },
    0X16: { args: 'V', pops: '', pushes: 'S', desc: 'Push extern string ref' },
    0X17: { args: 'V', pops: 'I', pushes: 'I', desc: 'Push extern int array ref' },
    0X18: { args: 'V', pops: 'I', pushes: 'F', desc: 'Push extern float array ref' },
    0X19: { args: 'V', pops: 'I', pushes: 'S', desc: 'Push extern string array ref' },
    0X1A: { args: 'B', pops: 'S', pushes: 'I', desc: 'Push file field int' },
    0X1B: { args: 'B', pops: 'S', pushes: 'F', desc: 'Push file field float' },
    0X1C: { args: 'B', pops: 'S', pushes: 'S', desc: 'Push file field string' },
    0X1D: { args: 'B', pops: 'S', pushes: 'I', desc: 'Push file field int ref' },
    0X1E: { args: 'B', pops: 'S', pushes: 'F', desc: 'Push file field float ref' },
    0X1F: { args: 'B', pops: 'S', pushes: 'S', desc: 'Push file field string ref' },
    0X20: { args: 'B', pops: '', pushes: 'I', desc: 'Push byte literal' },
    0X21: { args: 'I', pops: '', pushes: 'I', desc: 'Push word literal' },
    0X22: { args: 'I', pops: '', pushes: 'I', desc: 'Push integer literal' },
    0X23: { args: 'F', pops: '', pushes: 'F', desc: 'Push float literal' },
    0X24: { args: 'S', pops: '', pushes: 'S', desc: 'Push string literal' },
    0X25: { args: '', pops: '', pushes: '', desc: 'Machine Code Call' },
    0X26: { args: '', pops: '', pushes: '', desc: 'UT$LEAV' },
    0X27: { args: '', pops: 'I I', pushes: 'I', desc: '<' },
    0X28: { args: '', pops: 'I I', pushes: 'I', desc: '<=' },
    0X29: { args: '', pops: 'I I', pushes: 'I', desc: '>' },
    0X2A: { args: '', pops: 'I I', pushes: 'I', desc: '>=' },
    0X2B: { args: '', pops: 'I I', pushes: 'I', desc: '<>' },
    0X2C: { args: '', pops: 'I I', pushes: 'I', desc: '=' },
    0X2D: { args: '', pops: 'I I', pushes: 'I', desc: '+' },
    0X2E: { args: '', pops: 'I I', pushes: 'I', desc: '-' },
    0X2F: { args: '', pops: 'I I', pushes: 'I', desc: '*' },
    0X30: { args: '', pops: 'I I', pushes: 'I', desc: '/' },
    0X31: { args: '', pops: 'I I', pushes: 'I', desc: '**' },
    0X32: { args: '', pops: 'I', pushes: 'I', desc: '-' },
    0X33: { args: '', pops: 'I', pushes: 'I', desc: 'NOT' },
    0X34: { args: '', pops: 'I I', pushes: 'I', desc: 'AND' },
    0X35: { args: '', pops: 'I I', pushes: 'I', desc: 'OR' },
    0X36: { args: '', pops: 'F F', pushes: 'I', desc: '<' },
    0X37: { args: '', pops: 'F F', pushes: 'I', desc: '<=' },
    0X38: { args: '', pops: 'F F', pushes: 'I', desc: '>' },
    0X39: { args: '', pops: 'F F', pushes: 'I', desc: '>=' },
    0X3A: { args: '', pops: 'F F', pushes: 'I', desc: '<>' },
    0X3B: { args: '', pops: 'F F', pushes: 'I', desc: '=' },
    0X3C: { args: '', pops: 'F F', pushes: 'F', desc: '+' },
    0X3D: { args: '', pops: 'F F', pushes: 'F', desc: '-' },
    0X3E: { args: '', pops: 'F F', pushes: 'F', desc: '*' },
    0X3F: { args: '', pops: 'F F', pushes: 'F', desc: '/' },
    0X40: { args: '', pops: 'F F', pushes: 'F', desc: '**' },
    0X41: { args: '', pops: 'F', pushes: 'F', desc: '-' },
    0X42: { args: '', pops: 'F', pushes: 'I', desc: 'NOT' },
    0X43: { args: '', pops: 'F F', pushes: 'I', desc: 'AND' },
    0X44: { args: '', pops: 'F F', pushes: 'I', desc: 'OR' },
    0X45: { args: '', pops: 'S S', pushes: 'I', desc: '<' },
    0X46: { args: '', pops: 'S S', pushes: 'I', desc: '<=' },
    0X47: { args: '', pops: 'S S', pushes: 'I', desc: '>' },
    0X48: { args: '', pops: 'S S', pushes: 'I', desc: '>=' },
    0X49: { args: '', pops: 'S S', pushes: 'I', desc: '<>' },
    0X4A: { args: '', pops: 'S S', pushes: 'I', desc: '=' },
    0X4B: { args: '', pops: 'S S', pushes: 'S', desc: '+' },
    0X4C: { args: '', pops: 'I I', pushes: '', desc: 'AT' },
    0X4D: { args: '', pops: 'I I', pushes: '', desc: 'BEEP' },
    0X4E: { args: '', pops: '', pushes: '', desc: 'CLS' },
    0X4F: { args: 'O', pops: '', pushes: '', desc: 'CURSOR' },
    0X50: { args: 'O', pops: '', pushes: '', desc: 'ESCAPE' },
    0X51: { args: 'D', pops: '', pushes: '', desc: 'GOTO' },
    0X52: { args: '', pops: '', pushes: '', desc: 'OFF' },
    0X53: { args: 'D', pops: '', pushes: '', desc: 'ONERR' },
    0X54: { args: '', pops: 'I', pushes: '', desc: 'PAUSE' },
    0X55: { args: '', pops: 'I I', pushes: '', desc: 'POKEB' },
    0X56: { args: '', pops: 'I I', pushes: '', desc: 'POKEW' },
    0X57: { args: '', pops: 'I', pushes: '', desc: 'RAISE' },
    0X58: { args: '', pops: 'F', pushes: '', desc: 'RANDOMIZE' },
    0X59: { args: '', pops: '', pushes: '', desc: 'STOP' },
    0X5A: { args: '', pops: '', pushes: '', desc: 'TRAP' },
    0X5B: { args: '', pops: '', pushes: '', desc: 'APPEND' },
    0X5C: { args: '', pops: '', pushes: '', desc: 'CLOSE' },
    0X5D: { args: '', pops: 'S S', pushes: '', desc: 'COPY' },
    0X5E: { args: 'f+list', pops: 'S', pushes: '', desc: 'CREATE' },
    0X5F: { args: '', pops: 'S', pushes: '', desc: 'DELETE' },
    0X60: { args: '', pops: '', pushes: '', desc: 'ERASE' },
    0X61: { args: '', pops: '', pushes: '', desc: 'FIRST' },
    0X62: { args: '', pops: '', pushes: '', desc: 'LAST' },
    0X63: { args: '', pops: '', pushes: '', desc: 'NEXT' },
    0X64: { args: '', pops: '', pushes: '', desc: 'BACK' },
    0X65: { args: 'f+list', pops: 'S', pushes: '', desc: 'OPEN' },
    0X66: { args: '', pops: 'I', pushes: '', desc: 'POSITION' },
    0X67: { args: '', pops: 'S S', pushes: '', desc: 'RENAME' },
    0X68: { args: '', pops: '', pushes: '', desc: 'UPDATE' },
    0X69: { args: 'B', pops: '', pushes: '', desc: 'USE' },
    0X6A: { args: '', pops: 'I', pushes: '', desc: 'KSTAT' },
    0X6B: { args: '', pops: 'S', pushes: '', desc: 'EDIT' },
    0X6C: { args: '', pops: 'I', pushes: '', desc: 'INPUT' },
    0X6D: { args: '', pops: 'I', pushes: '', desc: 'INPUT' },
    0X6E: { args: '', pops: 'I', pushes: '', desc: 'INPUT' },
    0X6F: { args: '', pops: 'I', pushes: '', desc: 'PRINT' },
    0X70: { args: '', pops: 'F', pushes: '', desc: 'PRINT' },
    0X71: { args: '', pops: 'S', pushes: '', desc: 'PRINT' },
    0X72: { args: '', pops: '', pushes: '', desc: 'PRINT ,' },
    0X73: { args: '', pops: '', pushes: '', desc: 'PRINT (NL)' },
    0X74: { args: '', pops: 'I', pushes: '', desc: 'LPRINT' },
    0X75: { args: '', pops: 'F', pushes: '', desc: 'LPRINT' },
    0X76: { args: '', pops: 'S', pushes: '', desc: 'LPRINT' },
    0X77: { args: '', pops: '', pushes: '', desc: 'LPRINT ,' },
    0X78: { args: '', pops: '', pushes: '', desc: 'LPRINT (NL)' },
    0X79: { args: '', pops: '?', pushes: '', desc: 'RETURN' },
    0X7A: { args: '', pops: '', pushes: '', desc: 'RETURN' },
    0X7B: { args: '', pops: '', pushes: '', desc: 'RETURN' },
    0X7C: { args: '', pops: '', pushes: '', desc: 'RETURN' },
    0X7D: { args: 'params', pops: '', pushes: '?', desc: 'PROC' },
    0X7E: { args: 'D', pops: '', pushes: '', desc: 'BranchIfFalse' },
    0X7F: { args: '', pops: 'I I', pushes: '', desc: 'Assign Int' },
    0X80: { args: '', pops: 'I F', pushes: '', desc: 'Assign Float' },
    0X81: { args: '', pops: 'I S', pushes: '', desc: 'Assign String' },
    0X82: { args: '', pops: '', pushes: '', desc: 'DROP' },
    0X83: { args: '', pops: 'I', pushes: '', desc: 'DROP' },
    0X84: { args: '', pops: 'F', pushes: '', desc: 'DROP' },
    0X85: { args: '', pops: 'S', pushes: '', desc: 'DROP' },
    0X86: { args: '', pops: 'I', pushes: 'F', desc: 'FLT' },
    0X87: { args: '', pops: 'F', pushes: 'I', desc: 'INT' },
    0X88: { args: '', pops: '', pushes: '', desc: 'End of Field List' },
    0X89: { args: 'code', pops: '', pushes: '', desc: 'Inline Code' },
    0X8A: { args: '', pops: 'i', pushes: 'I', desc: 'ADDR' },
    0X8B: { args: '', pops: 'S', pushes: 'I', desc: 'ASC' },
    0X8C: { args: '', pops: '', pushes: 'I', desc: 'DAY' },
    0X8D: { args: '', pops: 'I S', pushes: 'I', desc: 'DISP' },
    0X8E: { args: '', pops: '', pushes: 'I', desc: 'ERR' },
    0X8F: { args: '', pops: 'S', pushes: 'I', desc: 'FIND' },
    0X90: { args: '', pops: '', pushes: 'I', desc: 'FREE' },
    0X91: { args: '', pops: '', pushes: 'I', desc: 'GET' },
    0X92: { args: '', pops: '', pushes: 'I', desc: 'HOUR' },
    0X93: { args: '', pops: 'I', pushes: 'I', desc: 'ABS' },
    0X94: { args: '', pops: 'F', pushes: 'I', desc: 'INT' },
    0X95: { args: '', pops: '', pushes: 'I', desc: 'KEY' },
    0X96: { args: '', pops: 'S', pushes: 'I', desc: 'LEN' },
    0X97: { args: '', pops: 'S S', pushes: 'I', desc: 'LOC' },
    0X98: { args: '', pops: 'S', pushes: 'I', desc: 'MENU' },
    0X99: { args: '', pops: '', pushes: 'I', desc: 'MINUTE' },
    0X9A: { args: '', pops: '', pushes: 'I', desc: 'MONTH' },
    0X9B: { args: '', pops: 'I', pushes: 'I', desc: 'PEEKB' },
    0X9C: { args: '', pops: 'I', pushes: 'I', desc: 'PEEKW' },
    0X9D: { args: '', pops: '', pushes: 'I', desc: 'RECSIZE' },
    0X9E: { args: '', pops: '', pushes: 'I', desc: 'SECOND' },
    0X9F: { args: '', pops: 'I I', pushes: 'I', desc: 'USR' },
    0XA0: { args: '', pops: 'I S', pushes: 'I', desc: 'VIEW' },
    0XA1: { args: '', pops: '', pushes: 'I', desc: 'YEAR' },
    0XA2: { args: '', pops: '', pushes: 'I', desc: 'COUNT' },
    0XA3: { args: '', pops: '', pushes: 'I', desc: 'EOF' },
    0XA4: { args: '', pops: 'S', pushes: 'I', desc: 'EXIST' },
    0XA5: { args: '', pops: '', pushes: 'I', desc: 'POS' },
    0XA6: { args: '', pops: 'F', pushes: 'F', desc: 'ABS' },
    0XA7: { args: '', pops: 'F', pushes: 'F', desc: 'ATAN' },
    0XA8: { args: '', pops: 'F', pushes: 'F', desc: 'COS' },
    0XA9: { args: '', pops: 'F', pushes: 'F', desc: 'DEG' },
    0XAA: { args: '', pops: 'F', pushes: 'F', desc: 'EXP' },
    0XAB: { args: '', pops: 'F', pushes: 'F', desc: 'FLT' },
    0XAC: { args: '', pops: 'F', pushes: 'F', desc: 'INTF' },
    0XAD: { args: '', pops: 'F', pushes: 'F', desc: 'LN' },
    0XAE: { args: '', pops: 'F', pushes: 'F', desc: 'LOG' },
    0XAF: { args: '', pops: '', pushes: 'F', desc: 'PI' },
    0XB0: { args: '', pops: 'F', pushes: 'F', desc: 'RAD' },
    0XB1: { args: '', pops: '', pushes: 'F', desc: 'RND' },
    0XB2: { args: '', pops: 'F', pushes: 'F', desc: 'SIN' },
    0XB3: { args: '', pops: 'F', pushes: 'F', desc: 'SQR' },
    0XB4: { args: '', pops: 'F', pushes: 'F', desc: 'TAN' },
    0XB5: { args: '', pops: 'S', pushes: 'F', desc: 'VAL' },
    0XB6: { args: '', pops: '', pushes: 'F', desc: 'SPACE' },
    0XB7: { args: '', pops: 'S', pushes: 'S', desc: 'DIR$' },
    0XB8: { args: '', pops: 'I', pushes: 'S', desc: 'CHR$' },
    0XB9: { args: '', pops: '', pushes: 'S', desc: 'DATIM$' },
    0XBA: { args: '', pops: '', pushes: 'S', desc: 'ERR$' },
    0XBB: { args: '', pops: 'F I I', pushes: 'S', desc: 'FIX$' },
    0XBC: { args: '', pops: 'F I', pushes: 'S', desc: 'GEN$' },
    0XBD: { args: '', pops: '', pushes: 'S', desc: 'GET$' },
    0XBE: { args: '', pops: 'I', pushes: 'S', desc: 'HEX$' },
    0XBF: { args: '', pops: '', pushes: 'S', desc: 'KEY$' },
    0XC0: { args: '', pops: 'S I', pushes: 'S', desc: 'LEFT$' },
    0XC1: { args: '', pops: 'S', pushes: 'S', desc: 'LOWER$' },
    0XC2: { args: '', pops: 'S I I', pushes: 'S', desc: 'MID$' },
    0XC3: { args: '', pops: 'F I', pushes: 'S', desc: 'NUM$' },
    0XC4: { args: '', pops: 'S I', pushes: 'S', desc: 'RIGHT$' },
    0XC5: { args: '', pops: 'S I', pushes: 'S', desc: 'REPT$' },
    0XC6: { args: '', pops: 'F I I', pushes: 'S', desc: 'SCI$' },
    0XC7: { args: '', pops: 'S', pushes: 'S', desc: 'UPPER$' },
    0XC8: { args: '', pops: 'I I', pushes: 'S', desc: 'USR$' },
    0XC9: { args: '', pops: 's', pushes: 'I', desc: 'ADDR' },
    0XCA: { args: 'S I', pops: '', pushes: '', desc: '.LNO' },
    0XCB: { args: 'I I', pops: '', pushes: '', desc: '.LNO' },
    0XCC: { args: '', pops: 'F F', pushes: 'F', desc: '<%' },
    0XCD: { args: '', pops: 'F F', pushes: 'F', desc: '>%' },
    0XCE: { args: '', pops: 'F F', pushes: 'F', desc: '+%' },
    0XCF: { args: '', pops: 'F F', pushes: 'F', desc: '-%' },
    0XD0: { args: '', pops: 'F F', pushes: 'F', desc: '*%' },
    0XD1: { args: '', pops: 'F F', pushes: 'F', desc: '/%' },
    0XD2: { args: '', pops: 'I', pushes: '', desc: 'OFF' },
    0XD3: { args: '', pops: 'S S', pushes: '', desc: 'COPYW' },
    0XD4: { args: '', pops: 'S', pushes: '', desc: 'DELETEW' },
    0XD5: { args: '', pops: 'I I I I I I I I I', pushes: '', desc: 'UDG' },
    0XD6: { args: '', pops: 'I', pushes: 'I', desc: 'CLOCK' },
    0XD7: { args: '', pops: 'I I I', pushes: 'I', desc: 'DOW' },
    0XD8: { args: '', pops: 'S', pushes: 'I', desc: 'FINDW' },
    0XD9: { args: '', pops: 'I S', pushes: 'I', desc: 'MENUN' },
    0XDA: { args: '', pops: 'I I I', pushes: 'I', desc: 'WEEK' },
    0XDB: { args: '', pops: 'F', pushes: 'F', desc: 'ACOS' },
    0XDC: { args: '', pops: 'F', pushes: 'F', desc: 'ASIN' },
    0XDD: { args: '', pops: 'I I I', pushes: 'F', desc: 'DAYS' },
    0XDE: { args: '', pops: 'Flist', pushes: 'F', desc: 'MAX' },
    0XDF: { args: '', pops: 'Flist', pushes: 'F', desc: 'MEAN' },
    0XE0: { args: '', pops: 'Flist', pushes: 'F', desc: 'MIN' },
    0XE1: { args: '', pops: 'Flist', pushes: 'F', desc: 'STD' },
    0XE2: { args: '', pops: 'Flist', pushes: 'F', desc: 'SUM' },
    0XE3: { args: '', pops: 'Flist', pushes: 'F', desc: 'VAR' },
    0XE4: { args: '', pops: 'I', pushes: 'S', desc: 'DAYNAME$' },
    0XE5: { args: '', pops: 'S', pushes: 'S', desc: 'DIRW$' },
    0XE6: { args: '', pops: 'I', pushes: 'S', desc: 'MONTH$' },
    0XEA: { args: '', pops: '', pushes: '', desc: 'REM Unknown EA' },
    0XED: { args: 'b', pops: '', pushes: '', desc: 'EXT' },
    0XEF: { args: 'v', pops: '', pushes: '', desc: 'REM LZ_EF' },
    0XFB: { args: 'D', pops: '', pushes: '', desc: 'ELSEIF' },
    0XFC: { args: '', pops: '', pushes: '', desc: 'REM LZ_FC' },
    0XFD: { args: '', pops: '', pushes: '', desc: 'REM LZ_FD' },
    0XFE: { args: 'prefix', pops: '', pushes: '', desc: 'Multi-byte Prefix' },
    0XFF: { args: '', pops: '', pushes: '', desc: 'CHECK' },
    0XF1: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F1' },
    0XF2: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F2' },
    0XF3: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F3' },
    0XF4: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F4' },
    0XF5: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F5' },
    0XF6: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F6' },
    0XF7: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F7' },
    0XF8: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F8' },
    0XF9: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_F9' },
    0XFA: { args: 'b b', pops: '', pushes: '', desc: 'POKE_M_FA' },
};

const FE_OPCODES = {
    0XD0: { args: 'v', pops: '', pushes: 'I', desc: 'Push local int' },
    0XD1: { args: 'v', pops: '', pushes: 'F', desc: 'Push local float' },
    0XD2: { args: 'v', pops: 'I', pushes: '', desc: 'Store local int' },
    0XD3: { args: 'v', pops: 'F', pushes: '', desc: 'Store local float' },
    0XD4: { args: 'v', pops: '', pushes: 'S', desc: 'Push local string' },
    0XD5: { args: 'v', pops: 'S', pushes: '', desc: 'Store local string' },
    0XD6: { args: 'v', pops: '', pushes: 'I', desc: 'Push local int ref' },
    0XD7: { args: 'v', pops: '', pushes: 'F', desc: 'Push local float ref' },
    0XD8: { args: 'v', pops: '', pushes: 'S', desc: 'Push local string ref' },
    0XD9: { args: 'v', pops: 'I', pushes: 'I', desc: 'Push local int array element' },
    0XDA: { args: 'v', pops: 'I', pushes: 'F', desc: 'Push local float array element' },
    0XDB: { args: 'v', pops: 'I', pushes: 'S', desc: 'Push local string array element' },
    0XDC: { args: 'v', pops: 'I', pushes: 'I', desc: 'Push local int array ref' },
    0XDD: { args: 'v', pops: 'I', pushes: 'F', desc: 'Push local float array ref' },
    0XDE: { args: 'v', pops: 'I', pushes: 'S', desc: 'Push local string array ref' },
};

const PRECEDENCE = {
    'OR': 1,
    'AND': 2,
    'NOT': 3,
    '=': 4, '<': 4, '>': 4, '<=': 4, '>=': 4, '<>': 4,
    '+': 5, '-': 5,
    '*': 6, '/': 6,
    '**': 7,
    'UNARY_MINUS': 8,
    'FUNC': 99,
    'ATOM': 99
};

if (typeof window !== 'undefined') {
    window.QCODE_DEFS = QCODE_DEFS;
    window.FE_OPCODES = FE_OPCODES;
    window.PRECEDENCE = PRECEDENCE;
}
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { QCODE_DEFS, FE_OPCODES, PRECEDENCE };
}
