/**
 * constants.js
 * 
 * OPL Decompiler Constants
 * Contains QCode definitions and Precedence rules.
 */

const QCODE_DEFS = {
    // Organiser II QCodes (Based on Jaap's documentation)
    0x00: { args: 'v', pops: '', pushes: 'I', desc: 'Push local/global int' },
    0x01: { args: 'v', pops: '', pushes: 'F', desc: 'Push local/global float' },
    0x02: { args: 'v', pops: '', pushes: 'S', desc: 'Push local/global string' },
    0x03: { args: 'V', pops: '', pushes: 'I', desc: 'Push local/global int array element' },
    0x04: { args: 'V', pops: '', pushes: 'F', desc: 'Push local/global float array element' },
    0x05: { args: 'V', pops: '', pushes: 'S', desc: 'Push local/global string array element' },
    0x06: { args: 'W', pops: '', pushes: 'F', desc: 'Push calculator memory' }, // W = 2 byte index (based on hex)
    0x07: { args: 'V', pops: '', pushes: 'I', desc: 'Push extern int' },
    0x08: { args: 'V', pops: '', pushes: 'F', desc: 'Push extern float' },
    0x09: { args: 'V', pops: '', pushes: 'S', desc: 'Push extern string' },
    0x0A: { args: 'V', pops: '', pushes: 'I', desc: 'Push extern int array element' },
    0x0B: { args: 'V', pops: '', pushes: 'F', desc: 'Push extern float array element' },
    0x0C: { args: 'V', pops: '', pushes: 'S', desc: 'Push extern string array element' },
    0x0D: { args: 'V', pops: '', pushes: 'I', desc: 'Push local/global int ref' },
    0x0E: { args: 'V', pops: '', pushes: 'F', desc: 'Push local/global float ref' },
    0x0F: { args: 'V', pops: '', pushes: 'S', desc: 'Push local/global string ref' },
    0x10: { args: 'V', pops: 'I', pushes: 'I', desc: 'Push local/global int array ref' },
    0x11: { args: 'V', pops: 'I', pushes: 'F', desc: 'Push local/global float array ref' },
    0x12: { args: 'V', pops: 'I', pushes: 'S', desc: 'Push local/global string array ref' },
    0x13: { args: 'W', pops: '', pushes: 'F', desc: 'Push calculator memory ref' },
    0x14: { args: 'V', pops: '', pushes: 'I', desc: 'Push extern int ref' },
    0x15: { args: 'V', pops: '', pushes: 'F', desc: 'Push extern float ref' },
    0x16: { args: 'V', pops: '', pushes: 'S', desc: 'Push extern string ref' },
    0x17: { args: 'V', pops: 'I', pushes: 'I', desc: 'Push extern int array ref' },
    0x18: { args: 'V', pops: 'I', pushes: 'F', desc: 'Push extern float array ref' },
    0x19: { args: 'V', pops: 'I', pushes: 'S', desc: 'Push extern string array ref' },
    0x1A: { args: 'B', pops: 'S', pushes: 'I', desc: 'Push file field int' }, // B = 1 byte logical name
    0x1B: { args: 'B', pops: 'S', pushes: 'F', desc: 'Push file field float' },
    0x1C: { args: 'B', pops: 'S', pushes: 'S', desc: 'Push file field string' },
    0x1D: { args: 'B', pops: 'S', pushes: 'I', desc: 'Push file field int ref' },
    0x1E: { args: 'B', pops: 'S', pushes: 'F', desc: 'Push file field float ref' },
    0x1F: { args: 'B', pops: 'S', pushes: 'S', desc: 'Push file field string ref' },
    0x20: { args: 'B', pops: '', pushes: 'I', desc: 'Push byte literal' },
    0x21: { args: 'I', pops: '', pushes: 'I', desc: 'Push word literal' },
    0x22: { args: 'I', pops: '', pushes: 'I', desc: 'Push integer literal' },
    0x23: { args: 'F', pops: '', pushes: 'F', desc: 'Push float literal' },
    0x24: { args: 'S', pops: '', pushes: 'S', desc: 'Push string literal' },
    0x25: { args: '', pops: '', pushes: '', desc: 'Machine Code Call' }, // Not used
    0x26: { args: '', pops: '', pushes: '', desc: 'UT$LEAV' }, // Not used
    0x27: { args: '', pops: 'I I', pushes: 'I', desc: '<' },
    0x28: { args: '', pops: 'I I', pushes: 'I', desc: '<=' },
    0x29: { args: '', pops: 'I I', pushes: 'I', desc: '>' },
    0x2A: { args: '', pops: 'I I', pushes: 'I', desc: '>=' },
    0x2B: { args: '', pops: 'I I', pushes: 'I', desc: '<>' },
    0x2C: { args: '', pops: 'I I', pushes: 'I', desc: '=' },
    0x2D: { args: '', pops: 'I I', pushes: 'I', desc: '+' },
    0x2E: { args: '', pops: 'I I', pushes: 'I', desc: '-' },
    0x2F: { args: '', pops: 'I I', pushes: 'I', desc: '*' },
    0x30: { args: '', pops: 'I I', pushes: 'I', desc: '/' },
    0x31: { args: '', pops: 'I I', pushes: 'I', desc: '**' },
    0x32: { args: '', pops: 'I', pushes: 'I', desc: '-' }, // Unary
    0x33: { args: '', pops: 'I', pushes: 'I', desc: 'NOT' },
    0x34: { args: '', pops: 'I I', pushes: 'I', desc: 'AND' },
    0x35: { args: '', pops: 'I I', pushes: 'I', desc: 'OR' },
    0x36: { args: '', pops: 'F F', pushes: 'I', desc: '<' },
    0x37: { args: '', pops: 'F F', pushes: 'I', desc: '<=' },
    0x38: { args: '', pops: 'F F', pushes: 'I', desc: '>' },
    0x39: { args: '', pops: 'F F', pushes: 'I', desc: '>=' },
    0x3A: { args: '', pops: 'F F', pushes: 'I', desc: '<>' },
    0x3B: { args: '', pops: 'F F', pushes: 'I', desc: '=' },
    0x3C: { args: '', pops: 'F F', pushes: 'F', desc: '+' },
    0x3D: { args: '', pops: 'F F', pushes: 'F', desc: '-' },
    0x3E: { args: '', pops: 'F F', pushes: 'F', desc: '*' },
    0x3F: { args: '', pops: 'F F', pushes: 'F', desc: '/' },
    0x40: { args: '', pops: 'F F', pushes: 'F', desc: '**' },
    0x41: { args: '', pops: 'F', pushes: 'F', desc: '-' }, // Unary
    0x42: { args: '', pops: 'F', pushes: 'I', desc: 'NOT' },
    0x43: { args: '', pops: 'F F', pushes: 'I', desc: 'AND' },
    0x44: { args: '', pops: 'F F', pushes: 'I', desc: 'OR' },
    0x45: { args: '', pops: 'S S', pushes: 'I', desc: '<' },
    0x46: { args: '', pops: 'S S', pushes: 'I', desc: '<=' },
    0x47: { args: '', pops: 'S S', pushes: 'I', desc: '>' },
    0x48: { args: '', pops: 'S S', pushes: 'I', desc: '>=' },
    0x49: { args: '', pops: 'S S', pushes: 'I', desc: '<>' },
    0x4A: { args: '', pops: 'S S', pushes: 'I', desc: '=' },
    0x4B: { args: '', pops: 'S S', pushes: 'S', desc: '+' },
    0x4C: { args: '', pops: 'I I', pushes: '', desc: 'AT' },
    0x4D: { args: '', pops: 'I I', pushes: '', desc: 'BEEP' },
    0x4E: { args: '', pops: '', pushes: '', desc: 'CLS' },
    0x4F: { args: 'O', pops: '', pushes: '', desc: 'CURSOR' },
    0x50: { args: 'O', pops: '', pushes: '', desc: 'ESCAPE' },
    0x51: { args: 'D', pops: '', pushes: '', desc: 'GOTO' },
    0x52: { args: '', pops: '', pushes: '', desc: 'OFF' },
    0x53: { args: 'D', pops: '', pushes: '', desc: 'ONERR' },
    0x54: { args: '', pops: 'I', pushes: '', desc: 'PAUSE' },
    0x55: { args: '', pops: 'I I', pushes: '', desc: 'POKEB' },
    0x56: { args: '', pops: 'I I', pushes: '', desc: 'POKEW' },
    0x57: { args: '', pops: 'I', pushes: '', desc: 'RAISE' },
    0x58: { args: '', pops: 'F', pushes: '', desc: 'RANDOMIZE' },
    0x59: { args: '', pops: '', pushes: '', desc: 'STOP' },
    0x5A: { args: '', pops: '', pushes: '', desc: 'TRAP' },
    0x5B: { args: '', pops: '', pushes: '', desc: 'APPEND' },
    0x5C: { args: '', pops: '', pushes: '', desc: 'CLOSE' },
    0x5D: { args: '', pops: 'S S', pushes: '', desc: 'COPY' },
    0x5E: { args: 'f+list', pops: 'S', pushes: '', desc: 'CREATE' },
    0x5F: { args: '', pops: 'S', pushes: '', desc: 'DELETE' },
    0x60: { args: '', pops: '', pushes: '', desc: 'ERASE' },
    0x61: { args: 'b', pops: '', pushes: '', desc: 'FIRST' },
    0x62: { args: 'b', pops: '', pushes: '', desc: 'LAST' },
    0x63: { args: 'b', pops: '', pushes: '', desc: 'NEXT' },
    0x64: { args: 'b', pops: '', pushes: '', desc: 'BACK' },
    0x65: { args: 'f+list', pops: 'S', pushes: '', desc: 'OPEN' },
    0x66: { args: '', pops: 'I', pushes: '', desc: 'POSITION' },
    0x67: { args: '', pops: 'S S', pushes: '', desc: 'RENAME' },
    0x68: { args: '', pops: '', pushes: '', desc: 'UPDATE' },
    0x69: { args: 'B', pops: '', pushes: '', desc: 'USE' },
    0x6A: { args: '', pops: 'I', pushes: '', desc: 'KSTAT' },
    0x6B: { args: '', pops: 'S', pushes: 'S', desc: 'EDIT' },
    0x6C: { args: '', pops: 'i', pushes: '', desc: 'INPUT' }, // integer var ref
    0x6D: { args: '', pops: 'f', pushes: '', desc: 'INPUT' }, // float var ref
    0x6E: { args: '', pops: 's', pushes: '', desc: 'INPUT' }, // string var ref
    0x6F: { args: '', pops: 'I', pushes: '', desc: 'PRINT' },
    0x70: { args: '', pops: 'F', pushes: '', desc: 'PRINT' },
    0x71: { args: '', pops: 'S', pushes: '', desc: 'PRINT' },
    0x72: { args: '', pops: '', pushes: '', desc: 'PRINT' }, // ,
    0x73: { args: '', pops: '', pushes: '', desc: 'PRINT' }, // newline
    0x74: { args: '', pops: 'I', pushes: '', desc: 'LPRINT' },
    0x75: { args: '', pops: 'F', pushes: '', desc: 'LPRINT' },
    0x76: { args: '', pops: 'S', pushes: '', desc: 'LPRINT' },
    0x77: { args: '', pops: '', pushes: '', desc: 'LPRINT' }, // ,
    0x78: { args: '', pops: '', pushes: '', desc: 'LPRINT' }, // newline
    0x79: { args: '', pops: '?', pushes: '', desc: 'RETURN' }, // Pops 1 value (Int, Float, String)
    0x7A: { args: '', pops: '', pushes: '', desc: 'RETURN' }, // 0
    0x7B: { args: '', pops: '', pushes: '', desc: 'RETURN' }, // 0.0 or Int constant? No args in user hex
    0x7C: { args: '', pops: '', pushes: '', desc: 'RETURN' }, // ""
    0x7D: { args: 'params', pops: '', pushes: '?', desc: 'PROC' },
    0x7E: { args: 'D', pops: 'I', pushes: '', desc: 'BranchIfFalse' },
    0x7F: { args: '', pops: 'i I', pushes: '', desc: 'Assign Int' },
    0x80: { args: '', pops: 'f F', pushes: '', desc: 'Assign Float' },
    0x81: { args: '', pops: 's S', pushes: '', desc: 'Assign String' },
    0x82: { args: '', pops: 'B', pushes: '', desc: 'DROP' },
    0x83: { args: '', pops: 'I', pushes: '', desc: 'DROP' },
    0x84: { args: '', pops: 'F', pushes: '', desc: 'DROP' },
    0x85: { args: '', pops: 'S', pushes: '', desc: 'DROP' },
    0x86: { args: '', pops: 'I', pushes: 'F', desc: 'FLT' }, // Auto conversion?
    0x87: { args: '', pops: 'F', pushes: 'I', desc: 'INT' }, // Auto conversion?
    0x88: { args: '', pops: '', pushes: '', desc: 'End of Field List' },
    0x89: { args: 'code', pops: '', pushes: '', desc: 'Inline Code' },
    0x8A: { args: '', pops: 'i', pushes: 'I', desc: 'ADDR' }, // int var ref
    0x8B: { args: '', pops: 'S', pushes: 'I', desc: 'ASC' },
    0x8C: { args: '', pops: '', pushes: 'I', desc: 'DAY' },
    0x8D: { args: '', pops: 'I S', pushes: 'I', desc: 'DISP' },
    0x8E: { args: '', pops: '', pushes: 'I', desc: 'ERR' },
    0x8F: { args: '', pops: 'S I', pushes: 'I', desc: 'FIND' },
    0x90: { args: '', pops: '', pushes: 'I', desc: 'FREE' },
    0x91: { args: '', pops: '', pushes: 'I', desc: 'GET' },
    0x92: { args: '', pops: '', pushes: 'I', desc: 'HOUR' },
    0x93: { args: '', pops: 'I', pushes: 'I', desc: 'ABS' },
    0x94: { args: '', pops: 'F', pushes: 'I', desc: 'INT' },
    0x95: { args: '', pops: '', pushes: 'I', desc: 'KEY' },
    0x96: { args: '', pops: 'S', pushes: 'I', desc: 'LEN' },
    0x97: { args: '', pops: 'S S', pushes: 'I', desc: 'LOC' },
    0x98: { args: '', pops: 'S', pushes: 'I', desc: 'MENU' },
    0x99: { args: '', pops: '', pushes: 'I', desc: 'MINUTE' },
    0x9A: { args: '', pops: '', pushes: 'I', desc: 'MONTH' },
    0x9B: { args: '', pops: 'I', pushes: 'I', desc: 'PEEKB' },
    0x9C: { args: '', pops: 'I', pushes: 'I', desc: 'PEEKW' },
    0x9D: { args: '', pops: '', pushes: 'I', desc: 'RECSIZE' },
    0x9E: { args: '', pops: '', pushes: 'I', desc: 'SECOND' },
    0x9F: { args: '', pops: 'I I', pushes: 'I', desc: 'USR' },
    0xA0: { args: '', pops: 'I S', pushes: 'I', desc: 'VIEW' },
    0xA1: { args: '', pops: '', pushes: 'I', desc: 'YEAR' },
    0xA2: { args: '', pops: '', pushes: 'I', desc: 'COUNT' },
    0xA3: { args: '', pops: '', pushes: 'I', desc: 'EOF' },
    0xA4: { args: '', pops: 'S', pushes: 'I', desc: 'EXIST' },
    0xA5: { args: '', pops: '', pushes: 'I', desc: 'POS' },
    0xA6: { args: '', pops: 'F', pushes: 'F', desc: 'ABS' },
    0xA7: { args: '', pops: 'F', pushes: 'F', desc: 'ATAN' },
    0xA8: { args: '', pops: 'F', pushes: 'F', desc: 'COS' },
    0xA9: { args: '', pops: 'F', pushes: 'F', desc: 'DEG' },
    0xAA: { args: '', pops: 'F', pushes: 'F', desc: 'EXP' },
    0xAB: { args: '', pops: 'F', pushes: 'F', desc: 'FLT' },
    0xAC: { args: '', pops: 'F', pushes: 'F', desc: 'INTF' },
    0xAD: { args: '', pops: 'F', pushes: 'F', desc: 'LN' },
    0xAE: { args: '', pops: 'F', pushes: 'F', desc: 'LOG' },
    0xAF: { args: '', pops: '', pushes: 'F', desc: 'PI' },
    0xB0: { args: '', pops: 'F', pushes: 'F', desc: 'RAD' },
    0xB1: { args: '', pops: '', pushes: 'F', desc: 'RND' },
    0xB2: { args: '', pops: 'F', pushes: 'F', desc: 'SIN' },
    0xB3: { args: '', pops: 'F', pushes: 'F', desc: 'SQR' },
    0xB4: { args: '', pops: 'F', pushes: 'F', desc: 'TAN' },
    0xB5: { args: '', pops: 'S', pushes: 'F', desc: 'VAL' },
    0xB6: { args: '', pops: '', pushes: 'F', desc: 'SPACE' },
    0xB7: { args: '', pops: 'S', pushes: 'S', desc: 'DIR$' },
    0xB8: { args: '', pops: 'I', pushes: 'S', desc: 'CHR$' },
    0xB9: { args: '', pops: '', pushes: 'S', desc: 'DATIM$' },
    0xBA: { args: '', pops: '', pushes: 'S', desc: 'ERR$' },
    0xBB: { args: '', pops: 'F I I', pushes: 'S', desc: 'FIX$' },
    0xBC: { args: '', pops: 'F I', pushes: 'S', desc: 'GEN$' },
    0xBD: { args: '', pops: '', pushes: 'S', desc: 'GET$' },
    0xBE: { args: '', pops: 'I', pushes: 'S', desc: 'HEX$' },
    0xBF: { args: '', pops: '', pushes: 'S', desc: 'KEY$' },
    0xC0: { args: '', pops: 'S I', pushes: 'S', desc: 'LEFT$' },
    0xC1: { args: '', pops: 'S', pushes: 'S', desc: 'LOWER$' },
    0xC2: { args: '', pops: 'S I I', pushes: 'S', desc: 'MID$' },
    0xC3: { args: '', pops: 'F I', pushes: 'S', desc: 'NUM$' },
    0xC4: { args: '', pops: 'S I', pushes: 'S', desc: 'RIGHT$' },
    0xC5: { args: '', pops: 'S I', pushes: 'S', desc: 'REPT$' },
    0xC6: { args: '', pops: 'F I I', pushes: 'S', desc: 'SCI$' },
    0xC7: { args: '', pops: 'S', pushes: 'S', desc: 'UPPER$' },
    0xC8: { args: '', pops: 'I I', pushes: 'S', desc: 'USR$' },
    0xC9: { args: '', pops: 's', pushes: 'I', desc: 'ADDR' }, // string var ref
    0xCA: { args: 'S I', pops: '', pushes: '', desc: '.LNO' }, // Used in .LNO
    0xCB: { args: 'I I', pops: '', pushes: '', desc: '.LNO' }, // Used in .LNO
    0xCC: { args: '', pops: 'F F', pushes: 'F', desc: '<%' },
    0xCD: { args: '', pops: 'F F', pushes: 'F', desc: '>%' },
    0xCE: { args: '', pops: 'F F', pushes: 'F', desc: '+%' },
    0xCF: { args: '', pops: 'F F', pushes: 'F', desc: '-%' },
    0xD0: { args: '', pops: 'F F', pushes: 'F', desc: '*%' },
    0xD1: { args: '', pops: 'F F', pushes: 'F', desc: '/%' },
    0xD2: { args: '', pops: 'I', pushes: '', desc: 'OFFX' },
    0xD3: { args: '', pops: 'S S', pushes: '', desc: 'COPYW' },
    0xD4: { args: '', pops: 'S', pushes: '', desc: 'DELETEW' },
    0xD5: { args: '', pops: 'I I I I I I I I I', pushes: '', desc: 'UDG' },
    0xD6: { args: '', pops: 'I', pushes: 'I', desc: 'CLOCK' },
    0xD7: { args: '', pops: 'I I I', pushes: 'I', desc: 'DOW' },
    0xD8: { args: '', pops: 'S', pushes: 'I', desc: 'FINDW' },
    0xD9: { args: '', pops: 'I S', pushes: 'I', desc: 'MENUN' },
    0xDA: { args: '', pops: 'I I I', pushes: 'I', desc: 'WEEK' },
    0xDB: { args: '', pops: 'F', pushes: 'F', desc: 'ACOS' },
    0xDC: { args: '', pops: 'F', pushes: 'F', desc: 'ASIN' },
    0xDD: { args: '', pops: 'I I', pushes: 'I', desc: 'FDAYS' },
    0x1B: { args: 'B', pops: 'S', pushes: 'F', desc: 'Push file field float' },
    0x1C: { args: 'B', pops: 'S', pushes: 'S', desc: 'Push file field string' },
    0x1D: { args: 'B', pops: 'S', pushes: 'I', desc: 'Push file field int ref' },
    0x1E: { args: 'B', pops: 'S', pushes: 'F', desc: 'Push file field float ref' },
    0x1F: { args: 'B', pops: 'S', pushes: 'S', desc: 'Push file field string ref' },
    0x20: { args: 'B', pops: '', pushes: 'I', desc: 'Push byte literal' },
    0x21: { args: 'I', pops: '', pushes: 'I', desc: 'Push word literal' },
    0x22: { args: 'I', pops: '', pushes: 'I', desc: 'Push integer literal' },
    0x23: { args: 'F', pops: '', pushes: 'F', desc: 'Push float literal' },
    0x24: { args: 'S', pops: '', pushes: 'S', desc: 'Push string literal' },
    0x25: { args: '', pops: '', pushes: '', desc: 'Machine Code Call' }, // Not used
    0x26: { args: '', pops: '', pushes: '', desc: 'UT$LEAV' }, // Not used
    0x27: { args: '', pops: 'I I', pushes: 'I', desc: '<' },
    0x28: { args: '', pops: 'I I', pushes: 'I', desc: '<=' },
    0x29: { args: '', pops: 'I I', pushes: 'I', desc: '>' },
    0x2A: { args: '', pops: 'I I', pushes: 'I', desc: '>=' },
    0x2B: { args: '', pops: 'I I', pushes: 'I', desc: '<>' },
    0x2C: { args: '', pops: 'I I', pushes: 'I', desc: '=' },
    0x2D: { args: '', pops: 'I I', pushes: 'I', desc: '+' },
    0x2E: { args: '', pops: 'I I', pushes: 'I', desc: '-' },
    0x2F: { args: '', pops: 'I I', pushes: 'I', desc: '*' },
    0x30: { args: '', pops: 'I I', pushes: 'I', desc: '/' },
    0x31: { args: '', pops: 'I I', pushes: 'I', desc: '**' },
    0x32: { args: '', pops: 'I', pushes: 'I', desc: '-' }, // Unary
    0x33: { args: '', pops: 'I', pushes: 'I', desc: 'NOT' },
    0x34: { args: '', pops: 'I I', pushes: 'I', desc: 'AND' },
    0x35: { args: '', pops: 'I I', pushes: 'I', desc: 'OR' },
    0x36: { args: '', pops: 'F F', pushes: 'I', desc: '<' },
    0x37: { args: '', pops: 'F F', pushes: 'I', desc: '<=' },
    0x38: { args: '', pops: 'F F', pushes: 'I', desc: '>' },
    0x39: { args: '', pops: 'F F', pushes: 'I', desc: '>=' },
    0x3A: { args: '', pops: 'F F', pushes: 'I', desc: '<>' },
    0x3B: { args: '', pops: 'F F', pushes: 'I', desc: '=' },
    0x3C: { args: '', pops: 'F F', pushes: 'F', desc: '+' },
    0x3D: { args: '', pops: 'F F', pushes: 'F', desc: '-' },
    0x3E: { args: '', pops: 'F F', pushes: 'F', desc: '*' },
    0x3F: { args: '', pops: 'F F', pushes: 'F', desc: '/' },
    0x40: { args: '', pops: 'F F', pushes: 'F', desc: '**' },
    0x41: { args: '', pops: 'F', pushes: 'F', desc: '-' }, // Unary
    0x42: { args: '', pops: 'F', pushes: 'I', desc: 'NOT' },
    0x43: { args: '', pops: 'F F', pushes: 'I', desc: 'AND' },
    0x44: { args: '', pops: 'F F', pushes: 'I', desc: 'OR' },
    0x45: { args: '', pops: 'S S', pushes: 'I', desc: '<' },
    0x46: { args: '', pops: 'S S', pushes: 'I', desc: '<=' },
    0x47: { args: '', pops: 'S S', pushes: 'I', desc: '>' },
    0x48: { args: '', pops: 'S S', pushes: 'I', desc: '>=' },
    0x49: { args: '', pops: 'S S', pushes: 'I', desc: '<>' },
    0x4A: { args: '', pops: 'S S', pushes: 'I', desc: '=' },
    0x4B: { args: '', pops: 'S S', pushes: 'S', desc: '+' },
    0x4C: { args: '', pops: 'I I', pushes: '', desc: 'AT' },
    0x4D: { args: '', pops: 'I I', pushes: '', desc: 'BEEP' },
    0x4E: { args: '', pops: '', pushes: '', desc: 'CLS' },
    0x4F: { args: 'O', pops: '', pushes: '', desc: 'CURSOR' },
    0x50: { args: 'O', pops: '', pushes: '', desc: 'ESCAPE' },
    0x51: { args: 'D', pops: '', pushes: '', desc: 'GOTO' },
    0x52: { args: '', pops: '', pushes: '', desc: 'OFF' },
    0x53: { args: 'D', pops: '', pushes: '', desc: 'ONERR' },
    0x54: { args: '', pops: 'I', pushes: '', desc: 'PAUSE' },
    0x55: { args: '', pops: 'I I', pushes: '', desc: 'POKEB' },
    0x56: { args: '', pops: 'I I', pushes: '', desc: 'POKEW' },
    0x57: { args: '', pops: 'I', pushes: '', desc: 'RAISE' },
    0x58: { args: 'F', pops: '', pushes: '', desc: 'RANDOMIZE' },
    0x59: { args: '', pops: '', pushes: '', desc: 'STOP' },
    0x5A: { args: '', pops: '', pushes: '', desc: 'TRAP' },
    0x5B: { args: '', pops: '', pushes: '', desc: 'APPEND' },
    0x5C: { args: '', pops: '', pushes: '', desc: 'CLOSE' },
    0x5D: { args: '', pops: 'S S', pushes: '', desc: 'COPY' },
    0x5E: { args: 'f+list', pops: 'S', pushes: '', desc: 'CREATE' },
    0x5F: { args: '', pops: 'S', pushes: '', desc: 'DELETE' },
    0x60: { args: '', pops: '', pushes: '', desc: 'ERASE' },
    0x61: { args: '', pops: '', pushes: '', desc: 'FIRST' },
    0x62: { args: '', pops: '', pushes: '', desc: 'LAST' },
    0x63: { args: '', pops: '', pushes: '', desc: 'NEXT' },
    0x64: { args: '', pops: '', pushes: '', desc: 'BACK' },
    0x65: { args: 'f+list', pops: 'S', pushes: '', desc: 'OPEN' },
    0x66: { args: '', pops: 'I', pushes: '', desc: 'POSITION' },
    0x67: { args: '', pops: 'S S', pushes: '', desc: 'RENAME' },
    0x68: { args: '', pops: '', pushes: '', desc: 'UPDATE' },
    0x69: { args: 'B', pops: '', pushes: '', desc: 'USE' },
    0x6A: { args: '', pops: 'I', pushes: '', desc: 'KSTAT' },
    0x6B: { args: '', pops: 'S', pushes: 'S', desc: 'EDIT' },
    0x6C: { args: '', pops: 'i', pushes: '', desc: 'INPUT' }, // integer var ref
    0x6D: { args: '', pops: 'f', pushes: '', desc: 'INPUT' }, // float var ref
    0x6E: { args: '', pops: 's', pushes: '', desc: 'INPUT' }, // string var ref
    0x6F: { args: '', pops: 'I', pushes: '', desc: 'PRINT' },
    0x70: { args: '', pops: 'F', pushes: '', desc: 'PRINT' },
    0x71: { args: '', pops: 'S', pushes: '', desc: 'PRINT' },
    0x72: { args: '', pops: '', pushes: '', desc: 'PRINT' }, // ,
    0x73: { args: '', pops: '', pushes: '', desc: 'PRINT' }, // newline
    0x74: { args: '', pops: 'I', pushes: '', desc: 'LPRINT' },
    0x75: { args: '', pops: 'F', pushes: '', desc: 'LPRINT' },
    0x76: { args: '', pops: 'S', pushes: '', desc: 'LPRINT' },
    0x77: { args: '', pops: '', pushes: '', desc: 'LPRINT' }, // ,
    0x78: { args: '', pops: '', pushes: '', desc: 'LPRINT' }, // newline
    0x79: { args: '', pops: '?', pushes: '', desc: 'RETURN' }, // Pops 1 value (Int, Float, String)
    0x7A: { args: '', pops: '', pushes: '', desc: 'RETURN' }, // 0
    0x7B: { args: '', pops: '', pushes: '', desc: 'RETURN' }, // 0.0 or Int constant? No args in user hex
    0x7C: { args: '', pops: '', pushes: '', desc: 'RETURN' }, // ""
    0x7D: { args: 'params', pops: '', pushes: '?', desc: 'PROC' },
    0x7E: { args: 'D', pops: 'I', pushes: '', desc: 'BranchIfFalse' },
    0x7F: { args: '', pops: 'i I', pushes: '', desc: 'Assign Int' },
    0x80: { args: '', pops: 'f F', pushes: '', desc: 'Assign Float' },
    0x81: { args: '', pops: 's S', pushes: '', desc: 'Assign String' },
    0x82: { args: '', pops: 'B', pushes: '', desc: 'DROP' },
    0x83: { args: '', pops: 'I', pushes: '', desc: 'DROP' },
    0x84: { args: '', pops: 'F', pushes: '', desc: 'DROP' },
    0x85: { args: '', pops: 'S', pushes: '', desc: 'DROP' },
    0x86: { args: '', pops: 'I', pushes: 'F', desc: 'FLT' }, // Auto conversion?
    0x87: { args: '', pops: 'F', pushes: 'I', desc: 'INT' }, // Auto conversion?
    0x88: { args: '', pops: '', pushes: '', desc: 'End of Field List' },
    0x89: { args: 'code', pops: '', pushes: '', desc: 'Inline Code' },
    0x8A: { args: '', pops: 'i', pushes: 'I', desc: 'ADDR' }, // int var ref
    0x8B: { args: '', pops: 'S', pushes: 'I', desc: 'ASC' },
    0x8C: { args: '', pops: '', pushes: 'I', desc: 'DAY' },
    0x8D: { args: '', pops: 'I S', pushes: 'I', desc: 'DISP' },
    0x8E: { args: '', pops: '', pushes: 'I', desc: 'ERR' },
    0x8F: { args: '', pops: 'S', pushes: 'I', desc: 'FIND' },
    0x90: { args: '', pops: '', pushes: 'I', desc: 'FREE' },
    0x91: { args: '', pops: '', pushes: 'I', desc: 'GET' },
    0x92: { args: '', pops: '', pushes: 'I', desc: 'HOUR' },
    0x93: { args: '', pops: 'I', pushes: 'I', desc: 'ABS' },
    0x94: { args: '', pops: 'F', pushes: 'I', desc: 'INT' },
    0x95: { args: '', pops: '', pushes: 'I', desc: 'KEY' },
    0x96: { args: '', pops: 'S', pushes: 'I', desc: 'LEN' },
    0x97: { args: '', pops: 'S S', pushes: 'I', desc: 'LOC' },
    0x98: { args: '', pops: 'S', pushes: 'I', desc: 'MENU' },
    0x99: { args: '', pops: '', pushes: 'I', desc: 'MINUTE' },
    0x9A: { args: '', pops: '', pushes: 'I', desc: 'MONTH' },
    0x9B: { args: '', pops: 'I', pushes: 'I', desc: 'PEEKB' },
    0x9C: { args: '', pops: 'I', pushes: 'I', desc: 'PEEKW' },
    0x9D: { args: '', pops: '', pushes: 'I', desc: 'RECSIZE' },
    0x9E: { args: '', pops: '', pushes: 'I', desc: 'SECOND' },
    0x9F: { args: '', pops: 'I I', pushes: 'I', desc: 'USR' },
    0xA0: { args: '', pops: 'I S', pushes: 'I', desc: 'VIEW' },
    0xA1: { args: '', pops: '', pushes: 'I', desc: 'YEAR' },
    0xA2: { args: '', pops: '', pushes: 'I', desc: 'COUNT' },
    0xA3: { args: '', pops: '', pushes: 'I', desc: 'EOF' },
    0xA4: { args: '', pops: 'S', pushes: 'I', desc: 'EXIST' },
    0xA5: { args: '', pops: '', pushes: 'I', desc: 'POS' },
    0xA6: { args: '', pops: 'F', pushes: 'F', desc: 'ABS' },
    0xA7: { args: '', pops: 'F', pushes: 'F', desc: 'ATAN' },
    0xA8: { args: '', pops: 'F', pushes: 'F', desc: 'COS' },
    0xA9: { args: '', pops: 'F', pushes: 'F', desc: 'DEG' },
    0xAA: { args: '', pops: 'F', pushes: 'F', desc: 'EXP' },
    0xAB: { args: '', pops: 'F', pushes: 'F', desc: 'FLT' },
    0xAC: { args: '', pops: 'F', pushes: 'F', desc: 'INTF' },
    0xAD: { args: '', pops: 'F', pushes: 'F', desc: 'LN' },
    0xAE: { args: '', pops: 'F', pushes: 'F', desc: 'LOG' },
    0xAF: { args: '', pops: '', pushes: 'F', desc: 'PI' },
    0xB0: { args: '', pops: 'F', pushes: 'F', desc: 'RAD' },
    0xB1: { args: '', pops: '', pushes: 'F', desc: 'RND' },
    0xB2: { args: '', pops: 'F', pushes: 'F', desc: 'SIN' },
    0xB3: { args: '', pops: 'F', pushes: 'F', desc: 'SQR' },
    0xB4: { args: '', pops: 'F', pushes: 'F', desc: 'TAN' },
    0xB5: { args: '', pops: 'S', pushes: 'F', desc: 'VAL' },
    0xB6: { args: '', pops: '', pushes: 'F', desc: 'SPACE' },
    0xB7: { args: '', pops: 'S', pushes: 'S', desc: 'DIR$' },
    0xB8: { args: '', pops: 'I', pushes: 'S', desc: 'CHR$' },
    0xB9: { args: '', pops: '', pushes: 'S', desc: 'DATIM$' },
    0xBA: { args: '', pops: '', pushes: 'S', desc: 'ERR$' },
    0xBB: { args: '', pops: 'F I I', pushes: 'S', desc: 'FIX$' },
    0xBC: { args: '', pops: 'F I', pushes: 'S', desc: 'GEN$' },
    0xBD: { args: '', pops: '', pushes: 'S', desc: 'GET$' },
    0xBE: { args: '', pops: 'I', pushes: 'S', desc: 'HEX$' },
    0xBF: { args: '', pops: '', pushes: 'S', desc: 'KEY$' },
    0xC0: { args: '', pops: 'S I', pushes: 'S', desc: 'LEFT$' },
    0xC1: { args: '', pops: 'S', pushes: 'S', desc: 'LOWER$' },
    0xC2: { args: '', pops: 'S I I', pushes: 'S', desc: 'MID$' },
    0xC3: { args: '', pops: 'F I', pushes: 'S', desc: 'NUM$' },
    0xC4: { args: '', pops: 'S I', pushes: 'S', desc: 'RIGHT$' },
    0xC5: { args: '', pops: 'S I', pushes: 'S', desc: 'REPT$' },
    0xC6: { args: '', pops: 'F I I', pushes: 'S', desc: 'SCI$' },
    0xC7: { args: '', pops: 'S', pushes: 'S', desc: 'UPPER$' },
    0xC8: { args: '', pops: 'I I', pushes: 'S', desc: 'USR$' },
    0xC9: { args: '', pops: 's', pushes: 'I', desc: 'ADDR' }, // string var ref
    0xCA: { args: 'S I', pops: '', pushes: '', desc: '.LNO' }, // Used in .LNO
    0xCB: { args: 'I I', pops: '', pushes: '', desc: '.LNO' }, // Used in .LNO
    0xCC: { args: '', pops: 'F F', pushes: 'F', desc: '<%' },
    0xCD: { args: '', pops: 'F F', pushes: 'F', desc: '>%' },
    0xCE: { args: '', pops: 'F F', pushes: 'F', desc: '+%' },
    0xCF: { args: '', pops: 'F F', pushes: 'F', desc: '-%' },
    0xD0: { args: '', pops: 'F F', pushes: 'F', desc: '*%' },
    0xD1: { args: '', pops: 'F F', pushes: 'F', desc: '/%' },
    0xD2: { args: '', pops: 'I', pushes: '', desc: 'OFFX' },
    0xD3: { args: '', pops: 'S S', pushes: '', desc: 'COPYW' },
    0xD4: { args: '', pops: 'S', pushes: '', desc: 'DELETEW' },
    0xD5: { args: '', pops: 'I I I I I I I I I', pushes: '', desc: 'UDG' },
    0xD6: { args: '', pops: 'I', pushes: 'I', desc: 'CLOCK' },
    0xD7: { args: '', pops: 'I I I', pushes: 'I', desc: 'DOW' },
    0xD8: { args: '', pops: 'S', pushes: 'I', desc: 'FINDW' },
    0xD9: { args: '', pops: 'I S', pushes: 'I', desc: 'MENUN' },
    0xDA: { args: '', pops: 'I I I', pushes: 'I', desc: 'WEEK' },
    0xDB: { args: '', pops: 'F', pushes: 'F', desc: 'ACOS' },
    0xDC: { args: '', pops: 'F', pushes: 'F', desc: 'ASIN' },
    0xDD: { args: '', pops: 'I I', pushes: 'I', desc: 'FDAYS' },
    0xDE: { args: '', pops: 'Flist', pushes: 'F', desc: 'MAX' },
    0xDF: { args: '', pops: 'Flist', pushes: 'F', desc: 'MEAN' },
    0xE0: { args: '', pops: 'Flist', pushes: 'F', desc: 'MIN' },
    0xE1: { args: '', pops: 'Flist', pushes: 'F', desc: 'STD' },
    0xE2: { args: '', pops: 'Flist', pushes: 'F', desc: 'SUM' },
    0xE3: { args: '', pops: 'Flist', pushes: 'F', desc: 'VAR' },
    0xED: { args: 'b', pops: '', pushes: '', desc: 'EXT' }, // Extended Opcode Prefix
    0xEF: { args: 'v', pops: '', pushes: '', desc: 'REM LZ_EF' }, // LZ Specific?
    0xFB: { args: 'D', pops: '', pushes: '', desc: 'ELSEIF' }, // LZ Specific
    0xFC: { args: '', pops: '', pushes: '', desc: 'REM LZ_FC' }, // LZ Specific
    0xFD: { args: '', pops: '', pushes: '', desc: 'REM LZ_FD' }, // LZ Specific
    0xFE: { args: '', pops: '', pushes: '', desc: 'REM LZ_FE' }, // LZ Specific (Prefix?)
    0xFF: { args: '', pops: '', pushes: '', desc: 'CHECK' }, // NOP/Check byte?
};
const PRECEDENCE = {
    'OR': 1,
    'AND': 2,
    'NOT': 3,
    '=': 4, '<': 4, '>': 4, '<=': 4, '>=': 4, '<>': 4,
    '+': 5, '-': 5,
    '*': 6, '/': 6,
    '**': 7,
    'UNARY_MINUS': 8,
    'FUNC': 99,
    'ATOM': 99
};

if (typeof window !== 'undefined') {
    window.QCODE_DEFS = QCODE_DEFS;
    window.PRECEDENCE = PRECEDENCE;
}
