/**
 * OPLCommandData.js
 * -----------------
 * Data source for the OPL Command Reference.
 * Contains command names, syntax, and compatibility flags.
 */

const OPL_COMMANDS = [
    { name: "ABS", syntax: "ABS(<exp>)", description: "Returns the absolute value of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "ACOS", syntax: "ACOS(<exp>)", description: "Returns the arc cosine of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "ADDR", syntax: "ADDR(<var>)", description: "Returns the address of the variable.", cm: true, xp: true, la: true, lz: true },
    { name: "AND", syntax: "<exp> AND <exp>", description: "Logical AND operator.", cm: true, xp: true, la: true, lz: true },
    { name: "APPEND", syntax: "APPEND", description: "Appends a new record to the current data file.", cm: true, xp: true, la: true, lz: true },
    { name: "ASC", syntax: "ASC(<exp$>)", description: "Returns the ASCII code of the first character of the string.", cm: true, xp: true, la: true, lz: true },
    { name: "ASIN", syntax: "ASIN(<exp>)", description: "Returns the arc sine of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "AT", syntax: "AT <x>,<y>", description: "Positions the cursor at the specified column and row.", cm: true, xp: true, la: true, lz: true },
    { name: "ATAN", syntax: "ATAN(<exp>)", description: "Returns the arc tangent of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "BEEP", syntax: "BEEP <duration>,<pitch>", description: "Produces a beep sound.", cm: true, xp: true, la: true, lz: true },
    { name: "BREAK", syntax: "BREAK", description: "Exits the current loop (DO...UNTIL or WHILE...ENDWH).", cm: true, xp: true, la: true, lz: true },
    { name: "BUSY", syntax: "BUSY <str$>", description: "Displays a busy message in the corner of the screen.", cm: false, xp: false, la: false, lz: true },
    { name: "CHR$", syntax: "CHR$(<exp>)", description: "Returns the character with the specified ASCII code.", cm: true, xp: true, la: true, lz: true },
    { name: "CLS", syntax: "CLS", description: "Clears the screen.", cm: true, xp: true, la: true, lz: true },
    { name: "COPY", syntax: "COPY <src$>,<dest$>", description: "Copies a file.", cm: true, xp: true, la: true, lz: true },
    { name: "COS", syntax: "COS(<exp>)", description: "Returns the cosine of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "COUNT", syntax: "COUNT", description: "Returns the number of records in the current data file.", cm: true, xp: true, la: true, lz: true },
    { name: "CREATE", syntax: "CREATE <file$>,<log>,<f1>,<f2>...", description: "Creates a new data file.", cm: true, xp: true, la: true, lz: true },
    { name: "CURSOR", syntax: "CURSOR <id>", description: "Switches the cursor on or off.", cm: true, xp: true, la: true, lz: true },
    { name: "DAY", syntax: "DAY", description: "Returns the current day of the month (1-31).", cm: true, xp: true, la: true, lz: true },
    { name: "DAYS", syntax: "DAYS(<d>,<m>,<y>)", description: "Returns the number of days from 1900 to the specified date.", cm: true, xp: true, la: true, lz: true },
    { name: "DELETE", syntax: "DELETE <file$>", description: "Deletes a file.", cm: true, xp: true, la: true, lz: true },
    { name: "DIR$", syntax: "DIR$(<path$>)", description: "Returns the first file matching the path pattern.", cm: true, xp: true, la: true, lz: true },
    { name: "DISP", syntax: "DISP <func>,<arg>", description: "Controls the display (e.g., contrast).", cm: true, xp: true, la: true, lz: true },
    { name: "DO", syntax: "DO ... UNTIL <cond>", description: "Starts a DO...UNTIL loop.", cm: true, xp: true, la: true, lz: true },
    { name: "DOW", syntax: "DOW(<d>,<m>,<y>)", description: "Returns the day of the week (1=Mon, 7=Sun).", cm: true, xp: true, la: true, lz: true },
    { name: "EDIT", syntax: "EDIT(<str$>)", description: "Allows the user to edit a string.", cm: true, xp: true, la: true, lz: true },
    { name: "ELSE", syntax: "IF...ELSE...ENDIF", description: "Alternative branch in an IF statement.", cm: true, xp: true, la: true, lz: true },
    { name: "ELSEIF", syntax: "IF...ELSEIF...ENDIF", description: "Alternative condition in an IF statement.", cm: false, xp: false, la: false, lz: true },
    { name: "ENDIF", syntax: "ENDIF", description: "Ends an IF statement.", cm: true, xp: true, la: true, lz: true },
    { name: "EOF", syntax: "EOF", description: "Returns true if the end of the data file has been reached.", cm: true, xp: true, la: true, lz: true },
    { name: "ERASE", syntax: "ERASE", description: "Erases the current record in the data file.", cm: true, xp: true, la: true, lz: true },
    { name: "ERR", syntax: "ERR", description: "Returns the error code of the last error.", cm: true, xp: true, la: true, lz: true },
    { name: "ERR$", syntax: "ERR$(<err>)", description: "Returns the error message for the specified error code.", cm: true, xp: true, la: true, lz: true },
    { name: "ESCAPE", syntax: "ESCAPE <state>", description: "Enables or disables the ON/CLEAR key break.", cm: true, xp: true, la: true, lz: true },
    { name: "EXIST", syntax: "EXIST(<file$>)", description: "Returns true if the file exists.", cm: true, xp: true, la: true, lz: true },
    { name: "EXP", syntax: "EXP(<exp>)", description: "Returns e raised to the power of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "EXT", syntax: "EXT <ext$>", description: "Loads a language extension.", cm: true, xp: true, la: true, lz: true },
    { name: "FIND", syntax: "FIND(<str$>)", description: "Finds a record containing the string.", cm: true, xp: true, la: true, lz: true },
    { name: "FIRST", syntax: "FIRST", description: "Moves to the first record in the data file.", cm: true, xp: true, la: true, lz: true },
    { name: "FIX$", syntax: "FIX$(<exp>,<fix>,<len>)", description: "Formats a number as a fixed-point string.", cm: true, xp: true, la: true, lz: true },
    { name: "FLT", syntax: "FLT(<exp>)", description: "Converts an integer to a floating-point number.", cm: true, xp: true, la: true, lz: true },
    { name: "FREE", syntax: "FREE", description: "Returns the amount of free memory.", cm: true, xp: true, la: true, lz: true },
    { name: "GEN$", syntax: "GEN$(<exp>,<len>)", description: "Formats a number as a general string.", cm: true, xp: true, la: true, lz: true },
    { name: "GET", syntax: "GET", description: "Waits for a keypress and returns its code.", cm: true, xp: true, la: true, lz: true },
    { name: "GET$", syntax: "GET$", description: "Waits for a keypress and returns it as a string.", cm: true, xp: true, la: true, lz: true },
    { name: "GOTO", syntax: "GOTO <label>", description: "Jumps to a label.", cm: true, xp: true, la: true, lz: true },
    { name: "HEX$", syntax: "HEX$(<exp>)", description: "Returns the hexadecimal representation of a number.", cm: true, xp: true, la: true, lz: true },
    { name: "HOUR", syntax: "HOUR", description: "Returns the current hour (0-23).", cm: true, xp: true, la: true, lz: true },
    { name: "IABS", syntax: "IABS(<exp>)", description: "Returns the absolute value of an integer.", cm: true, xp: true, la: true, lz: true },
    { name: "IF", syntax: "IF <cond> ... ENDIF", description: "Starts an IF statement.", cm: true, xp: true, la: true, lz: true },
    { name: "INPUT", syntax: "INPUT <var>", description: "Inputs a value into a variable.", cm: true, xp: true, la: true, lz: true },
    { name: "INT", syntax: "INT(<exp>)", description: "Truncates a number to an integer.", cm: true, xp: true, la: true, lz: true },
    { name: "INTF", syntax: "INTF(<exp>)", description: "Rounds a number to the nearest integer.", cm: true, xp: true, la: true, lz: true },
    { name: "KEY", syntax: "KEY", description: "Returns the code of the key currently pressed, or 0.", cm: true, xp: true, la: true, lz: true },
    { name: "KEY$", syntax: "KEY$", description: "Returns the key currently pressed as a string, or empty.", cm: true, xp: true, la: true, lz: true },
    { name: "KMOD", syntax: "KMOD", description: "Returns the state of the modifier keys (Shift, Ctrl, etc.).", cm: true, xp: true, la: true, lz: true },
    { name: "LAST", syntax: "LAST", description: "Moves to the last record in the data file.", cm: true, xp: true, la: true, lz: true },
    { name: "LEFT$", syntax: "LEFT$(<str$>,<len>)", description: "Returns the leftmost characters of a string.", cm: true, xp: true, la: true, lz: true },
    { name: "LEN", syntax: "LEN(<str$>)", description: "Returns the length of a string.", cm: true, xp: true, la: true, lz: true },
    { name: "LN", syntax: "LN(<exp>)", description: "Returns the natural logarithm of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "LOC", syntax: "LOC(<str$>,<sub$>)", description: "Returns the position of a substring within a string.", cm: true, xp: true, la: true, lz: true },
    { name: "LOCAL", syntax: "LOCAL <var1>,<var2>...", description: "Declares local variables.", cm: true, xp: true, la: true, lz: true },
    { name: "LOG", syntax: "LOG(<exp>)", description: "Returns the base-10 logarithm of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "LOWER$", syntax: "LOWER$(<str$>)", description: "Converts a string to lowercase.", cm: true, xp: true, la: true, lz: true },
    { name: "LPRINT", syntax: "LPRINT <exp>", description: "Prints to the printer port.", cm: true, xp: true, la: true, lz: true },
    { name: "MAX", syntax: "MAX(<list>)", description: "Returns the maximum value in a list.", cm: true, xp: true, la: true, lz: true },
    { name: "MENU", syntax: "MENU(<str$>)", description: "Displays a menu and returns the selected item.", cm: true, xp: true, la: true, lz: true },
    { name: "MID$", syntax: "MID$(<str$>,<pos>,<len>)", description: "Returns a substring.", cm: true, xp: true, la: true, lz: true },
    { name: "MIN", syntax: "MIN(<list>)", description: "Returns the minimum value in a list.", cm: true, xp: true, la: true, lz: true },
    { name: "MINUTE", syntax: "MINUTE", description: "Returns the current minute (0-59).", cm: true, xp: true, la: true, lz: true },
    { name: "MONTH", syntax: "MONTH", description: "Returns the current month (1-12).", cm: true, xp: true, la: true, lz: true },
    { name: "MONTH$", syntax: "MONTH$(<m>)", description: "Returns the name of the month.", cm: true, xp: true, la: true, lz: true },
    { name: "NEXT", syntax: "NEXT", description: "Moves to the next record in the data file.", cm: true, xp: true, la: true, lz: true },
    { name: "NOT", syntax: "NOT <exp>", description: "Logical NOT operator.", cm: true, xp: true, la: true, lz: true },
    { name: "NUM$", syntax: "NUM$(<exp>,<len>)", description: "Formats a number as an integer string.", cm: true, xp: true, la: true, lz: true },
    { name: "OFF", syntax: "OFF", description: "Switches the machine off.", cm: true, xp: true, la: true, lz: true },
    { name: "ONERR", syntax: "ONERR <label>", description: "Sets an error handler.", cm: true, xp: true, la: true, lz: true },
    { name: "OPEN", syntax: "OPEN <file$>,<log>,<f1>...", description: "Opens an existing data file.", cm: true, xp: true, la: true, lz: true },
    { name: "OR", syntax: "<exp> OR <exp>", description: "Logical OR operator.", cm: true, xp: true, la: true, lz: true },
    { name: "PAUSE", syntax: "PAUSE <ticks>", description: "Pauses execution for a number of 1/20th seconds.", cm: true, xp: true, la: true, lz: true },
    { name: "PEEKB", syntax: "PEEKB(<addr>)", description: "Returns the byte at the specified address.", cm: true, xp: true, la: true, lz: true },
    { name: "PEEKW", syntax: "PEEKW(<addr>)", description: "Returns the word at the specified address.", cm: true, xp: true, la: true, lz: true },
    { name: "PI", syntax: "PI", description: "Returns the value of Pi.", cm: true, xp: true, la: true, lz: true },
    { name: "POKEB", syntax: "POKEB <addr>,<byte>", description: "Writes a byte to the specified address.", cm: true, xp: true, la: true, lz: true },
    { name: "POKEW", syntax: "POKEW <addr>,<word>", description: "Writes a word to the specified address.", cm: true, xp: true, la: true, lz: true },
    { name: "POS", syntax: "POS", description: "Returns the current record number.", cm: true, xp: true, la: true, lz: true },
    { name: "POSITION", syntax: "POSITION <n>", description: "Moves to the specified record number.", cm: true, xp: true, la: true, lz: true },
    { name: "PRINT", syntax: "PRINT <exp>", description: "Prints to the screen.", cm: true, xp: true, la: true, lz: true },
    { name: "PROC", syntax: "PROC <name>:", description: "Starts a procedure definition.", cm: true, xp: true, la: true, lz: true },
    { name: "RAD", syntax: "RAD(<exp>)", description: "Converts degrees to radians.", cm: true, xp: true, la: true, lz: true },
    { name: "RAISE", syntax: "RAISE <err>", description: "Raises an error.", cm: true, xp: true, la: true, lz: true },
    { name: "RANDOMIZE", syntax: "RANDOMIZE <seed>", description: "Seeds the random number generator.", cm: true, xp: true, la: true, lz: true },
    { name: "REC", syntax: "REC", description: "Returns the size of the current record.", cm: true, xp: true, la: true, lz: true },
    { name: "RECSZ", syntax: "RECSZ", description: "Returns the size of the current record.", cm: true, xp: true, la: true, lz: true },
    { name: "REM", syntax: "REM <text>", description: "Comment.", cm: true, xp: true, la: true, lz: true },
    { name: "RENAME", syntax: "RENAME <old$>,<new$>", description: "Renames a file.", cm: true, xp: true, la: true, lz: true },
    { name: "REPT", syntax: "REPT(<str$>,<n>)", description: "Repeats a string n times.", cm: true, xp: true, la: true, lz: true },
    { name: "RETURN", syntax: "RETURN <exp>", description: "Returns from a procedure.", cm: true, xp: true, la: true, lz: true },
    { name: "RIGHT$", syntax: "RIGHT$(<str$>,<len>)", description: "Returns the rightmost characters of a string.", cm: true, xp: true, la: true, lz: true },
    { name: "RND", syntax: "RND", description: "Returns a random number between 0 and 1.", cm: true, xp: true, la: true, lz: true },
    { name: "SCI$", syntax: "SCI$(<exp>,<fix>,<len>)", description: "Formats a number in scientific notation.", cm: true, xp: true, la: true, lz: true },
    { name: "SCREEN", syntax: "SCREEN <w>,<h>", description: "Sets the screen size (LZ only).", cm: false, xp: false, la: false, lz: true },
    { name: "SECOND", syntax: "SECOND", description: "Returns the current second (0-59).", cm: true, xp: true, la: true, lz: true },
    { name: "SIN", syntax: "SIN(<exp>)", description: "Returns the sine of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "SPACE", syntax: "SPACE", description: "Returns the amount of free space on the current device.", cm: true, xp: true, la: true, lz: true },
    { name: "SQR", syntax: "SQR(<exp>)", description: "Returns the square root of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "STOP", syntax: "STOP", description: "Stops execution.", cm: true, xp: true, la: true, lz: true },
    { name: "TAN", syntax: "TAN(<exp>)", description: "Returns the tangent of the expression.", cm: true, xp: true, la: true, lz: true },
    { name: "TRAP", syntax: "TRAP <command>", description: "Traps errors from the following command.", cm: true, xp: true, la: true, lz: true },
    { name: "UDG", syntax: "UDG <c>,<v1>...", description: "Defines a user-defined graphic.", cm: true, xp: true, la: true, lz: true },
    { name: "UNTIL", syntax: "UNTIL <cond>", description: "Ends a DO...UNTIL loop.", cm: true, xp: true, la: true, lz: true },
    { name: "UPDATE", syntax: "UPDATE", description: "Updates the current record in the data file.", cm: true, xp: true, la: true, lz: true },
    { name: "UPPER$", syntax: "UPPER$(<str$>)", description: "Converts a string to uppercase.", cm: true, xp: true, la: true, lz: true },
    { name: "USE", syntax: "USE <log>", description: "Selects the current data file.", cm: true, xp: true, la: true, lz: true },
    { name: "USR", syntax: "USR(<addr>,<ax>)", description: "Calls a machine code subroutine.", cm: true, xp: true, la: true, lz: true },
    { name: "USR$", syntax: "USR$(<addr>,<ax>)", description: "Calls a machine code function returning a string.", cm: true, xp: true, la: true, lz: true },
    { name: "VAL", syntax: "VAL(<str$>)", description: "Converts a string to a number.", cm: true, xp: true, la: true, lz: true },
    { name: "VIEW", syntax: "VIEW(<n>,<str$>)", description: "Displays a view window.", cm: true, xp: true, la: true, lz: true },
    { name: "WHILE", syntax: "WHILE <cond> ... ENDWH", description: "Starts a WHILE loop.", cm: true, xp: true, la: true, lz: true },
    { name: "YEAR", syntax: "YEAR", description: "Returns the current year.", cm: true, xp: true, la: true, lz: true }
];

if (typeof window !== 'undefined') {
    window.OPL_COMMANDS = OPL_COMMANDS;
}
